# Generated by Django 6.0.6 on 2026-06-12 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='آرمان فارما', max_length=100, verbose_name='site name')),
                ('site_tagline', models.CharField(default='سلامت، اعتماد، کیفیت', max_length=255, verbose_name='site tagline')),
                ('phone', models.CharField(default='۰۲۱-۸۸۸۸۸۸۸۸', max_length=20, verbose_name='phone number')),
                ('email', models.EmailField(default='info@armanpharma.com', max_length=254, verbose_name='email')),
                ('address', models.TextField(default='تهران، خیابان ولیعصر، نرسیده به ونک، پلاک ۱۲۳', verbose_name='address')),
                ('working_hours', models.CharField(default='شنبه تا پنجشنبه: ۸ صبح تا ۱۰ شب', max_length=255, verbose_name='working hours')),
                ('express_shipping_cost', models.PositiveIntegerField(default=45000, verbose_name='express shipping cost')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com', null=True)),
                ('telegram', models.URLField(blank=True, default='https://t.me', null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('theme_color', models.CharField(default='#0ea5e9', help_text='مانند #0ea5e9', max_length=7, verbose_name='primary theme color (hex)')),
                ('about_us_text', models.TextField(default='آرمان فارما، داروخانه آنلاین شما با ارائه بهترین و با کیفیت\u200cترین محصولات بهداشتی و دارویی، همواره در تلاش است تا تجربه\u200cای امن و سریع را برای شما فراهم آورد.', verbose_name='about us text')),
                ('hero_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product', verbose_name='hero product')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
