# Generated by Django 6.0.6 on 2026-06-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='order ID')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='transaction ID')),
                ('gateway_name', models.CharField(max_length=50, verbose_name='gateway name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='gateway payload')),
                ('callback_data', models.JSONField(blank=True, null=True, verbose_name='callback data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
