# Generated by Django 6.0.6 on 2026-06-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('address', models.TextField(verbose_name='address')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipping', 'Shipping'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('shipping_method', models.CharField(choices=[('express', 'Express (2-4 hours)'), ('standard', 'Standard (24 hours)')], default='standard', max_length=20, verbose_name='shipping method')),
                ('payment_method', models.CharField(choices=[('gateway', 'Online Payment'), ('cod', 'Cash on Delivery')], default='gateway', max_length=20, verbose_name='payment method')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='shipping cost')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='total price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
    ]
