# Generated by Django 6.0.6 on 2026-06-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='dosage form'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_strength',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='dosage strength'),
        ),
        migrations.AddField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='generic name'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_prescription_required',
            field=models.BooleanField(default=False, verbose_name='is prescription required'),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='usage instructions'),
        ),
        migrations.AddField(
            model_name='product',
            name='warnings',
            field=models.TextField(blank=True, null=True, verbose_name='warnings'),
        ),
    ]
